name: card_loading
description: A Flutter package to create easy create loading card between two colors
version: 0.0.1
homepage: https://github.com/farhanfadila1717/card_loading
maintener: Farhan Fadila (@farhanfadila1717)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
